# DO NOT EDIT THIS FILE!
# Edit scale_viridis.R and run ./scale_viridis_variants.sh

#' Magma colors
#'
#' The \code{magma} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @format A vector of length 256 containing hex values.
#' @source \url{https://bids.github.io/colormap/} for the concept and \url{https://github.com/BIDS/colormap/blob/master/colormaps.py} for the data.
#' @family mpl palettes
"magma"


#' Magma color scale and palette
#'
#' The \code{magma} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @inheritParams interp_scale
#'
#' @template return_scales
#'
#' @export
#'
#' @family color scales and palettes
#'
#' @seealso \code{\link{magma}} for the colors in the palette.
#'
#' @examples
#' # Get a few colors along the palette
#' show_col(
#'   magma_palette()(20),
#'   magma_colors(50),
#'   magma_colors(20, reverse=TRUE)
#' )
#'
#' # 1/ Represent a continuous variable
#'
#' # Map the elevation of the Maunga Whau volcano
#' image(maunga, col=magma_colors(100), asp=1)
#' contour(maunga, col=alpha("white", 0.5), add=TRUE)
#'
#' persp(maunga, theta=50, phi=25, scale=FALSE, expand=2,
#'       border=alpha("black", 0.4),
#'       col=magma_map(persp_facets(maunga$z)))
#'
#' \dontrun{
#' # with ggplot2
#' library("ggplot2")
#' ggplot(maungaxyz) + coord_fixed() +
#'   geom_raster(aes(x=x, y=y, fill=z)) +
#'   geom_contour(aes(x=x, y=y, z=z), color="white", alpha=0.5) +
#'   scale_fill_magma()
#'
#' # in spinning 3D
#' library("rgl")
#' persp3d(maunga, aspect=c(1,0.7,0.2), axes=FALSE, box=FALSE,
#'         col=magma_map(maunga$z))
#' play3d(spin3d(axis=c(0, 0, 1), rpm=10), duration=6)}
#'
#' # Represent a third variable on a scatterplot
#' attach(airquality)
#' # define a scale encompassing the whole data
#' my_scale <- magma_scale(domain=c(0,200))
#' # use the same scale for the plot and the legend
#' pars <- sidemargin()
#' plot(Wind, Temp, col=my_scale(Ozone), pch=19)
#' sidelegend(legend=c(pretty(Ozone), "NA"),
#'            col=my_scale(c(pretty(Ozone), NA)), pch=19)
#' par(pars)
#'
#' \dontrun{
#' # or with ggplot2
#' # but the light yellows at the top of the scale are difficult to see
#' # on points; either outline them or put them on a dark background
#' ggplot(airquality) +
#'   geom_point(aes(x=Wind, y=Temp, fill=Ozone), shape=21, size=2) +
#'   scale_fill_magma()
#' ggplot(airquality) + theme_dark() +
#'   geom_point(aes(x=Wind, y=Temp, color=Ozone)) +
#'   scale_color_magma(na.value="grey60")}
#'
#'
#' # 2/ Represent a discrete variable
#' # albeit only with a limited number of levels
#'
#' attach(iris)
#' pars <- sidemargin()
#' plot(Petal.Length, Petal.Width, pch=21, bg=magma_map(Species))
#' sidelegend(legend=levels(Species),
#'            pt.bg=magma_colors(n=nlevels(Species)), pch=21)
#' par(pars)
#'
#' \dontrun{
#' # or with ggplot2
#' ggplot(iris) +
#'   geom_point(aes(Petal.Length, Petal.Width, fill=Species), shape=21) +
#'   scale_fill_magma_d()}
magma_scale <- function(domain=c(0,1), reverse=FALSE, na.value=NULL, extrapolate=FALSE) {
  # get everything into numbers
  domain <- as.num(domain)
  if (reverse) { domain <- rev(domain)}
  f <- function(x) {
    x <- as.num(x)
    # compute colors
    xs <- rescale(x, from=domain, to=c(0,1))
    colors <- scales::colour_ramp(chroma::magma)(xs)
    return(post_process_scale(colors, magma_na(na.value), extrapolate, x, domain))
  }
  return(f)
}

#' @param ... passed to \code{\link{magma_scale}} from other \code{magma_*} functions; passed to \code{ggplot2::\link[ggplot2]{continuous_scale}} or \code{ggplot2::\link[ggplot2]{discrete_scale}} from the \code{scale_*} functions, as appropriate. NB: in all situations, passing \code{domain} is meaningless and yields an error.
#' @rdname magma_scale
#' @export
magma_map <- function(x, ...) { as_map(magma_scale, x,  ...) }

#' @rdname magma_scale
#' @export
magma_palette <- function(...) { as_palette(magma_scale, ...) }

#' @param n number of colors to extract from the color palette.
#' @rdname magma_scale
#' @export
magma_colors <- function(n, ...) { magma_palette(...)(n) }

# Pick and appropriate NA value for a magma scale
magma_na <- function(na.value) {
  if (is.null(na.value)) {
    na.value <- desaturate(average(magma_colors(50)), 10)
    # = grey of luminance equal to the average color of the scale
  }
  return(na.value)
}


## ggplot2 ----

#' @rdname magma_scale
#' @export
scale_color_magma_c <- function(..., reverse=FALSE, na.value=NULL, guide="colorbar") {
  cols <- if(reverse) rev(chroma::magma) else chroma::magma
  ggplot2::continuous_scale("colour", "magma",
    scales::colour_ramp(cols),
    na.value=magma_na(na.value), guide=guide, ...
  )
}
#' @rdname magma_scale
#' @export
#' @usage NULL
scale_colour_magma_c <- scale_color_magma_c

#' @rdname magma_scale
#' @export
scale_fill_magma_c <- function(..., reverse=FALSE, na.value="#818181", guide="colorbar") {
  cols <- if(reverse) rev(chroma::magma) else chroma::magma
  ggplot2::continuous_scale("fill", "magma",
    scales::colour_ramp(cols),
    na.value=magma_na(na.value), guide=guide, ...
  )
}

#' @rdname magma_scale
#' @export
scale_color_magma_d <- function(..., reverse=FALSE, na.value="#818181", guide="legend") {
  cols <- if(reverse) rev(chroma::magma) else chroma::magma
  ggplot2::discrete_scale("colour", "magma",
    function(n) {scales::colour_ramp(cols)(seq(0,1,length.out=n))},
    na.value=na.value, ...
  )
}
#' @rdname magma_scale
#' @export
#' @usage NULL
scale_colour_magma_d <- scale_color_magma_d

#' @rdname magma_scale
#' @export
scale_fill_magma_d <- function(..., reverse=FALSE, na.value="#818181", guide="legend") {
  cols <- if(reverse) rev(chroma::magma) else chroma::magma
  ggplot2::discrete_scale("fill", "magma",
    function(n) {scales::colour_ramp(cols)(seq(0,1,length.out=n))},
    na.value=na.value, ...
  )
}

# Make the continuous versions the default because it is the most common use case
#' @rdname magma_scale
#' @export
#' @usage NULL
scale_fill_magma <- scale_fill_magma_c
#' @rdname magma_scale
#' @export
#' @usage NULL
scale_color_magma <- scale_color_magma_c
#' @rdname magma_scale
#' @export
#' @usage NULL
scale_colour_magma <- scale_color_magma_c


