#!/bin/bash

prepend="# DO NOT EDIT THIS FILE!#NEWLINE## Edit scale_viridis.R and run ./scale_viridis_variants.sh#NEWLINE#"

sed -e "s/, Stefan van der Walt, and Eric Firing/ and Stefan van der Walt/g" -e "s/viridis/magma/g" -e "s/Viridis/Magma/g" -e "1s;^;$prepend#NEWLINE#;" -e 's/#NEWLINE#/\'$'\n/g' scale_viridis.R > scale_magma.R
sed -e "s/, Stefan van der Walt, and Eric Firing/ and Stefan van der Walt/g" -e "s/viridis/inferno/g" -e "s/Viridis/Magma/g" -e "1s;^;$prepend#NEWLINE#;" -e 's/#NEWLINE#/\'$'\n/g' scale_viridis.R > scale_inferno.R
sed -e "s/, Stefan van der Walt, and Eric Firing/ and Stefan van der Walt/g" -e "s/viridis/plasma/g" -e "s/Viridis/Magma/g" -e "1s;^;$prepend#NEWLINE#;" -e 's/#NEWLINE#/\'$'\n/g'  scale_viridis.R > scale_plasma.R

# NB: see http://nlfiedler.github.io/2010/12/05/newlines-in-sed-on-mac.html for the complex sed command and the #NEWLINE# bit
