# DO NOT EDIT THIS FILE!
# Edit scale_viridis.R and run ./scale_viridis_variants.sh

#' Magma colors
#'
#' The \code{inferno} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @format A vector of length 256 containing hex values.
#' @source \url{https://bids.github.io/colormap/} for the concept and \url{https://github.com/BIDS/colormap/blob/master/colormaps.py} for the data.
#' @family mpl palettes
"inferno"


#' Magma color scale and palette
#'
#' The \code{inferno} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @inheritParams make_scale 
#'
#' @template return_scales
#'
#' @family color scales and palettes
#'
#' @examples
#' # get a few colors along the palette
#' show_col(
#'   inferno_palette()(20),
#'   inferno_colors(50),
#'   inferno_colors(20, reverse=TRUE)
#' )
#' 
#' # Maunga Whau volcano elevation map
#' x <- 10*(1:nrow(volcano))
#' y <- 10*(1:ncol(volcano))
#' image(x, y, volcano, col=inferno_colors(100))
#' persp(x, y, volcano, theta=60, phi=25, border=NA,
#'       col=inferno_map(persp_facets(volcano)))
#' \dontrun{
#' library("rgl")
#' persp3d(x, y, volcano, aspect=c(1,0.6,0.3), axes=FALSE, box=FALSE,
#'         col=inferno_map(volcano))
#' play3d(spin3d(axis=c(0, 0, 1), rpm=10), duration=6)
#'
#' }
#' # with a limited number of levels, inferno can also serve as a discrete
#' # color scale
#' attach(iris)
#' plot(Petal.Length, Sepal.Length, pch=19, col=inferno_map(Species))
#' legend(1, 8, legend=levels(Species), pch=19, col=inferno_colors(n=nlevels(Species)))
#'
#' @export
inferno_scale <- function(domain=c(0,1), reverse=FALSE) {
  make_scale(colors=chroma::inferno, model="lab", interp="linear", domain=domain, reverse=reverse)
}

#' @param ... passed to \code{\link{inferno_scale}}. Note that argument \code{domain} is meaningless in functions other than \code{inferno_scale} and passing it through \code{...} is an error.
#' @name inferno_scale
#' @export
inferno_palette <- function(...) {
  make_palette(colors=chroma::inferno, model="lab", interp="linear", ...)
}

#' @name inferno_scale
#' @export
inferno_colors <- function(n, ...) {
  inferno_colors(n=n, colors=chroma::inferno, model="lab", interp="linear",...)
}
#' @name inferno_scale
#' @export
inferno.colors <- inferno_colors

#' @name inferno_scale
#' @export
inferno_map <- function(x, ...) {
  make_map(x, colors=chroma::inferno, model="lab", interp="linear", ...)
}
