# DO NOT EDIT THIS FILE!
# Edit scale_viridis.R and run ./scale_viridis_variants.sh

#' Magma colors
#'
#' The \code{magma} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @format A vector of length 256 containing hex values.
#' @source \url{https://bids.github.io/colormap/} for the concept and \url{https://github.com/BIDS/colormap/blob/master/colormaps.py} for the data.
#' @family mpl palettes
"magma"


#' Magma color scale and palette
#'
#' The \code{magma} color palette, by Nathaniel J. Smith and Stefan van der Walt (CC0 license).
#'
#' @inheritParams interp_scale
#'
#' @template return_scales
#'
#' @family color scales and palettes
#'
#' @seealso \code{\link{magma}} for the colors in the palette.
#'
#' @examples
#' # Get a few colors along the palette
#' show_col(
#'   magma_palette()(20),
#'   magma_colors(50),
#'   magma_colors(20, reverse=TRUE)
#' )
#'
#' # Plot the Maunga Whau volcano elevation map
#' image(maunga, col=magma_colors(100))
#' contour(maunga, col=alpha("black", 0.2), add=TRUE)
#'
#' persp(maunga, theta=50, phi=25, border=alpha("black", 0.3),
#'       col=magma_map(persp_facets(maunga$z)))
#'
#' \dontrun{library("rgl")
#' persp3d(maunga, aspect=c(1,0.6,0.3), axes=FALSE, box=FALSE,
#'         col=magma_map(maunga$z))
#' play3d(spin3d(axis=c(0, 0, 1), rpm=10), duration=6)
#' }
#' # With a limited number of levels, magma can also serve as a discrete
#' # color scale
#' attach(iris)
#' plot(Petal.Length, Sepal.Length, pch=19, col=magma_map(Species))
#' legend(1, 8, legend=levels(Species), pch=19,
#'        col=magma_colors(n=nlevels(Species)))
#'
#' @export
magma_scale <- function(domain=c(0,1), reverse=FALSE) {
  interp_scale(colors=chroma::magma, model="lab", interp="linear", domain=domain, reverse=reverse)
}

#' @param ... passed to \code{\link{magma_scale}}. Note that argument \code{domain} is meaningless in functions other than \code{magma_scale} and passing it through \code{...} is an error.
#' @name magma_scale
#' @export
magma_map <- function(x, ...) {
  interp_map(x, colors=chroma::magma, model="lab", interp="linear", ...)
}

#' @name magma_scale
#' @export
magma_palette <- function(...) {
  interp_palette(colors=chroma::magma, model="lab", interp="linear", ...)
}

#' @name magma_scale
#' @export
magma_colors <- function(n, ...) {
  interp_colors(n=n, colors=chroma::magma, model="lab", interp="linear",...)
}
#' @name magma_scale
#' @export
magma.colors <- magma_colors

